version: 2.1


# The machine we'll run on
# Just use base, since we do builds in docker anyway
executors:
  base_exec:
    resource_class: small
    docker:
      - image: cimg/base:edge-20.04


# Commands for logically separate tasks
# We use commands over jobs since we don't have Docker layer caching
commands:

  # Setup steps
  # Checkout the code and startup docker
  setup:
    description: Setting up the environment
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: Login to docker
          command: |
            echo "${DOCKER_PASSWORD}" | \
            docker login --username ammrat13 --password-stdin

  # Build the image
  build:
    description: Build the Docker image
    steps:
      - run:
          name: Build the Docker image
          command: |
            docker build \
              --tag ammrat13/gba-toolchain:latest \
              --file docker/gba-toolchain/Dockerfile \
              .

  # Push the image
  deploy:
    description: Push the Docker image
    steps:
      - run:
          name: Push the Docker image
          command: |
            docker push ammrat13/gba-toolchain:latest


# The different jobs for different branches
# Again, we can't use Docker layer caching
jobs:

  build_test:
    executor: base_exec
    steps:
      - setup
      - build

  build_test_deploy:
    executor: base_exec
    steps:
      - setup
      - build
      - deploy


# A workflow that specifies the actions we need to take
# Conditionally do different jobs depending on the branch
workflows:
  do_actions:
    jobs:

      # Deploy if on master
      - build_test_deploy:
          filters:
            branches:
              only: master

      # Otherwise, just build and test
      - build_test:
          filters:
            branches:
              ignore: master
